from django.urls import path

from staffConsole.views.lecturer import (
    LecturerDashboardView,
    ClassListView,
    StudentDetailAjaxView,
    MyCourseView,
    MyTimetableView,
    EnterResultsView,
    AssessmentStudentsAjaxView,
    SaveScoreAjaxView,
    AddAssessmentAjaxView,
    DeleteAssessmentAjaxView,
    BulkSaveScoresAjaxView,
    ExportTemplateView,
    InvigilationDutiesView,
    LecturerProfileDetailView,
    LecturerProfileUpdateAjaxView,
    SendBulkEmailView,
    SendStudentEmailView,
    LockTransmitAjaxView,
    SchemeImpactAjaxView,
    ApplySchemeAjaxView,
    ClassListDataAjaxView,
    ClassListRecipientsAjaxView,
    ClassListExportView,
    ImportScoresAjaxView
)

urlpatterns = [
    path(
        'dashboard/',
        LecturerDashboardView.as_view(), name='lecturer-dashboard'
    ),
    path(
        'class-list/',
        ClassListView.as_view(),
        name='lecturer-class-list'
    ),
    path(
        'class-list/student/<uuid:enrollment_id>/',
        StudentDetailAjaxView.as_view(),
        name='lecturer-student-detail'
    ),
    path(
        'class-list/send-email/',
        SendStudentEmailView.as_view(),
        name='lecturer-send-student-email'
    ),
    path(
        'class-list/data/',
        ClassListDataAjaxView.as_view(),
        name='lecturer-class-list-data'
    ),
    path(
        'class-list/recipients/',
        ClassListRecipientsAjaxView.as_view(),
        name='lecturer-class-list-recipients'
    ),
    path(
        'class-list/export/',
        ClassListExportView.as_view(),
        name='lecturer-class-list-export'
    ),
    path(
        'class-list/send-bulk-email/',
        SendBulkEmailView.as_view(),
        name='lecturer-send-bulk-email'
    ),
    path(
        'courses/',
        MyCourseView.as_view(),
        name='lecturer-courses'
    ),
    path(
        'timetable/',
        MyTimetableView.as_view(),
        name='lecturer-timetable'
    ),
    path(
        'enter-results/',
        EnterResultsView.as_view(),
        name='lecturer-enter-results'
    ),


    path(
        'results/assessment-students/',
        AssessmentStudentsAjaxView.as_view(),
        name='lecturer-assessment-students'
    ),
    path(
        'results/save-score/',
        SaveScoreAjaxView.as_view(),
        name='lecturer-save-score'
    ),
    path(
        'results/add-assessment/',
        AddAssessmentAjaxView.as_view(),
        name='lecturer-add-assessment'
    ),
    path(
        'results/delete-assessment/',
        DeleteAssessmentAjaxView.as_view(),
        name='lecturer-delete-assessment'
    ),
    path(
        'results/bulk-save/',
        BulkSaveScoresAjaxView.as_view(),
        name='lecturer-bulk-save-scores'
    ),
    path(
        'results/export-template/',
        ExportTemplateView.as_view(),
        name='lecturer-export-template'
    ),
    path(
        'results/import-scores/',
        ImportScoresAjaxView.as_view(),
        name="lecturer-import-scores"
    ),
    path(
        'invigilation/',
        InvigilationDutiesView.as_view(),
        name='lecturer-invigilation'
    ),
    path(
        'profile/',
        LecturerProfileDetailView.as_view(),
        name='lecturer-profile-details'
    ),
    path(
        'profile/update/',
        LecturerProfileUpdateAjaxView.as_view(),
        name='lecturer-profile-update'
    ),

    path(
        'results/lock-transmit/',
        LockTransmitAjaxView.as_view(),
        name='lecturer-lock-results'
    ),
    path(
        'results/scheme-impact/',
        SchemeImpactAjaxView.as_view(),
        name='lecturer-results-scheme-impact'
    ),
    path(
        'results/apply-scheme/',
        ApplySchemeAjaxView.as_view(),
        name='lecturer-results-apply-scheme'
    ),
]
