# Generated by Django 4.0.10 on 2026-05-30 10:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=78, null=True)),
                ('last_name', models.CharField(max_length=78, null=True)),
                ('surname', models.CharField(max_length=78, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=20)),
                ('profile_picture', models.ImageField(blank=True, default='profiles/profile.jpg', null=True, upload_to='profiles/')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('admin', 'Admin')], max_length=20)),
                ('is_activated', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=74, unique=True)),
                ('type', models.CharField(choices=[('C', 'Core'), ('E', 'Elective'), ('CC', 'Common Unit')], default='C', max_length=45)),
                ('credits', models.IntegerField(default=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=123)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=25)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_records', to='base.curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('breakdown', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_number', models.CharField(max_length=20, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='base.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('programme_name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=78)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_year', models.CharField(max_length=9)),
                ('semester', models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Semester 3')], max_length=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('academic_year', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marital_status', models.CharField(choices=[('M', 'Married'), ('U', 'Unmarried')], default='U', max_length=20)),
                ('name_of_spouse', models.CharField(blank=True, max_length=255, null=True)),
                ('spouse_contact', models.CharField(blank=True, max_length=19, null=True)),
                ('occupation_of_spouse', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_children', models.IntegerField(blank=True, null=True)),
                ('father_name', models.CharField(max_length=255)),
                ('father_id_type', models.CharField(choices=[('national', 'national Id'), ('passport', 'passport'), ('birthCert', 'Birth Certificate')], default='national', max_length=24)),
                ('father_id_no', models.CharField(default='xxxxxxx', max_length=34)),
                ('father_date_of_birth', models.DateField(default=datetime.date(2000, 4, 12))),
                ('mother_name', models.CharField(max_length=255)),
                ('mother_id_type', models.CharField(choices=[('national', 'national Id'), ('passport', 'passport'), ('birthCert', 'Birth Certificate')], default='national', max_length=24)),
                ('mother_id_no', models.CharField(default='xxxxxxx', max_length=34)),
                ('mother_date_of_birth', models.DateField(default=datetime.date(2000, 4, 12))),
                ('id_type', models.CharField(choices=[('national', 'national Id'), ('passport', 'passport'), ('birthCert', 'Birth Certificate')], default='national', max_length=24)),
                ('national_id', models.CharField(default='xxxxxxx', max_length=34, unique=True)),
                ('religion', models.CharField(default='pagan', max_length=34)),
                ('nationality', models.CharField(default='Kenyan', max_length=34)),
                ('ethnicity', models.CharField(default=' ', max_length=34)),
                ('date_of_birth', models.DateField(default=datetime.date(2000, 4, 12))),
                ('place_of_birth', models.CharField(default='', max_length=255)),
                ('telephone_no', models.CharField(default='07xxxxx', max_length=78)),
                ('school_email', models.EmailField(default='example@inst.com', max_length=254, unique=True)),
                ('domicile', models.CharField(default='kenya', max_length=78)),
                ('county', models.CharField(default='kenya', max_length=78)),
                ('sub_county', models.CharField(default='kenya', max_length=78)),
                ('constituency', models.CharField(default='kenya', max_length=78)),
                ('division', models.CharField(default='', max_length=78)),
                ('location', models.CharField(default='kenya', max_length=78)),
                ('home_adress', models.CharField(default='kenya', max_length=78)),
                ('emergency_contact_name', models.CharField(default='john', max_length=78)),
                ('emergency_contact_phone', models.CharField(default='07xxxxx', max_length=78)),
                ('emergency_contact_email', models.CharField(default='guardianeaxample.com', max_length=78)),
                ('emergency_contact_relationship', models.CharField(default='Guardian', max_length=78)),
                ('emergency_contact_address', models.CharField(default='home-0097-br-street', max_length=78, null=True)),
                ('emergency_contact_2_name', models.CharField(default='john', max_length=78)),
                ('emergency_contact_2_phone', models.CharField(default='07xxxxx', max_length=78)),
                ('emergency_contact_2_email', models.CharField(default='guardianeaxample.com', max_length=78)),
                ('emergency_contact_2_relationship', models.CharField(default='Guardian', max_length=78)),
                ('emergency_contact_2_address', models.CharField(default='home-0097-br-street', max_length=78, null=True)),
                ('registration_number', models.CharField(default='programme/000/2X', max_length=78, unique=True)),
                ('stay', models.CharField(choices=[('resident', 'Resident'), ('outside', 'Outside')], default='resident', max_length=78)),
                ('hostel', models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B'), ('c', 'C')], max_length=78, null=True)),
                ('enrolled', models.DateTimeField(auto_now_add=True)),
                ('deffered', models.BooleanField(default=False)),
                ('graduated', models.DateField(blank=True, null=True)),
                ('name_of_secondary_school', models.CharField(max_length=78)),
                ('address_of_secondary_school', models.CharField(max_length=255)),
                ('year_of_study', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tclass',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=78)),
                ('courses', models.ManyToManyField(through='base.Curriculum', to='base.course')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.programme')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentFeeAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.feestructure')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_accounts', to='base.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_accounts', to='base.student')),
            ],
            options={
                'unique_together': {('student', 'session')},
            },
        ),
        migrations.AddField(
            model_name='student',
            name='class_entered',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.tclass'),
        ),
        migrations.AddField(
            model_name='student',
            name='enrollments',
            field=models.ManyToManyField(blank=True, related_name='enrolled_students', through='base.Enrollment', to='base.curriculum'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SchoolAdmin',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_number', models.CharField(max_length=20, unique=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='base.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='school',
            name='active_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.session'),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('C', 'Cat'), ('E', 'Exams')], default='C', max_length=45)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('title', models.CharField(max_length=124)),
                ('curricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.curriculum')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='programme',
            name='current_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_class', to='base.tclass'),
        ),
        migrations.AddField(
            model_name='programme',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='base.department'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('cash', 'Cash')], max_length=10)),
                ('transaction_ref', models.CharField(max_length=100, unique=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='base.studentfeeaccount')),
            ],
            options={
                'unique_together': {('transaction_ref', 'method')},
            },
        ),
        migrations.CreateModel(
            name='OverDraft',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_account', to='base.studentfeeaccount')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.payment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstitutionAdmin',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_number', models.CharField(max_length=20, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='feestructure',
            name='Tclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='base.tclass'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='base.session'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_records', to='base.student'),
        ),
        migrations.CreateModel(
            name='DeptAdmin',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_number', models.CharField(max_length=20, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='base.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='department',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='base.school'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='Tclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.tclass'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.course'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='professor',
            field=models.ManyToManyField(blank=True, to='base.lecturer'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='results',
            field=models.ManyToManyField(through='base.Result', to='base.student'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.session'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, to='base.course'),
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('venue', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.course')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.lecturer')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.session')),
                ('tclass', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.tclass')),
            ],
            options={
                'unique_together': {('session', 'lecturer', 'day', 'start_time'), ('session', 'venue', 'day', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='Reporting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('reported_via', models.CharField(choices=[('online', 'Online'), ('physical', 'Physical')], max_length=10)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportings', to='base.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportings', to='base.student')),
            ],
            options={
                'unique_together': {('student', 'session')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('Tclass', 'session')},
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'curriculum')},
        ),
        migrations.AlterUniqueTogether(
            name='curriculum',
            unique_together={('course', 'Tclass', 'session')},
        ),
    ]
