# Generated by Django 6.0.5 on 2026-06-03 12:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeferredStudent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.student',),
        ),
        migrations.CreateModel(
            name='ResidentStudent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.student',),
        ),
        migrations.RemoveField(
            model_name='student',
            name='emergency_contact_2_address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='emergency_contact_2_email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='emergency_contact_2_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='emergency_contact_2_phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='emergency_contact_2_relationship',
        ),
        migrations.RemoveField(
            model_name='student',
            name='emergency_contact_address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='emergency_contact_email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='emergency_contact_relationship',
        ),
        migrations.RemoveField(
            model_name='student',
            name='father_date_of_birth',
        ),
        migrations.RemoveField(
            model_name='student',
            name='father_id_no',
        ),
        migrations.RemoveField(
            model_name='student',
            name='father_id_type',
        ),
        migrations.RemoveField(
            model_name='student',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='graduated',
        ),
        migrations.RemoveField(
            model_name='student',
            name='hostel',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mother_date_of_birth',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mother_id_no',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mother_id_type',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='year_of_study',
        ),
        migrations.AlterUniqueTogether(
            name='studentfeeaccount',
            unique_together={('student', 'fee_structure')},
        ),
        migrations.AddField(
            model_name='course',
            name='offered',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='title',
            field=models.CharField(choices=[('Graduate Assistant', 'GA'), ('Teaching Assistant', 'TA'), ('Tutorial Fellow', 'TF'), ('Assistant Lecturer', 'Asst. Lec.'), ('Junior Lecturer', 'Jr. Lec.'), ('Lecturer', 'Lec.'), ('Senior Lecturer', 'Snr. Lec.'), ('Associate Professor', 'Assoc. Prof.'), ('Professor', 'Prof.'), ('Full Professor', 'Full Prof.'), ('Distinguished Professor', 'Dist. Prof.'), ('Emeritus Professor', 'Prof. Emeritus'), ('Adjunct Lecturer', 'Adj. Lec.'), ('Visiting Lecturer', 'Vis. Lec.'), ('Guest Lecturer', 'Guest Lec.'), ('Part-Time Lecturer', 'PT Lec.'), ('Head of Department', 'HOD'), ('Dean of Faculty', 'Dean'), ('Director of School', 'Director'), ('Chaired Professor', 'Chair Prof.')], default='Lecturer', max_length=23),
        ),
        migrations.AddField(
            model_name='programme',
            name='degree_type',
            field=models.CharField(choices=[('BSc', 'Bachelor of Science'), ('BEd', 'Bachelor of Education'), ('LLB', 'Bachelor of Laws'), ('BA', 'Bachelor of Arts'), ('BCom', 'Bachelor of Commerce'), ('BBIT', 'Bachelor of Business Information Technology'), ('B.Arch', 'Bachelor of Architecture'), ('BEng', 'Bachelor of Engineering'), ('MBChB', 'Bachelor of Medicine and Bachelor of Surgery'), ('BPharm', 'Bachelor of Pharmacy'), ('BDS', 'Bachelor of Dental Surgery'), ('PGDE', 'Post Graduate Diploma in Education'), ('MSc', 'Master of Science'), ('MA', 'Master of Arts'), ('MBA', 'Master of Business Administration'), ('LLM', 'Master of Laws'), ('MEd', 'Master of Education'), ('MPH', 'Master of Public Health'), ('PhD', 'Doctor of Philosophy'), ('MD', 'Doctor of Medicine')], default=None, max_length=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programme',
            name='duration_years',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='programme',
            name='semesters_per_year',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='tclass',
            name='graduated',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tclass',
            name='year_of_study',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.CreateModel(
            name='HostelWarden',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_number', models.CharField(max_length=20, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=78)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('mixed', 'Mixed')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hostels', to='base.school')),
                ('warden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_hostels', to='base.hostelwarden')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParentGuardian',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('id_type', models.CharField(choices=[('national', 'national Id'), ('passport', 'passport'), ('birthCert', 'Birth Certificate')], max_length=24)),
                ('id_no', models.CharField(max_length=34)),
                ('date_of_birth', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='base.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=20)),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('triple', 'Triple'), ('ensuite', 'En-suite')], max_length=10)),
                ('capacity', models.IntegerField(default=2)),
                ('floor', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='base.hostel')),
            ],
            options={
                'unique_together': {('hostel', 'room_number')},
            },
        ),
        migrations.RemoveField(
            model_name='studentfeeaccount',
            name='session',
        ),
        migrations.CreateModel(
            name='Deferment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('financial', 'Financial Difficulty'), ('medical', 'Medical'), ('personal', 'Personal'), ('academic', 'Academic'), ('other', 'Other')], default='personal', max_length=20)),
                ('reason_detail', models.TextField(blank=True, help_text='Free text — additional context from registrar', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('reinstated', 'Reinstated'), ('withdrawn', 'Withdrawn')], default='active', max_length=15)),
                ('reinstated_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_deferments', to=settings.AUTH_USER_MODEL)),
                ('session_deferred', models.ForeignKey(help_text='The session the student deferred from', on_delete=django.db.models.deletion.PROTECT, related_name='deferments', to='base.session')),
                ('session_returning', models.ForeignKey(blank=True, help_text='The session the student is expected to return', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returning_students', to='base.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deferments', to='base.student')),
            ],
            options={
                'unique_together': {('student', 'session_deferred')},
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=78)),
                ('phone', models.CharField(max_length=78)),
                ('email', models.CharField(max_length=78)),
                ('relationship', models.CharField(max_length=78)),
                ('address', models.CharField(max_length=78, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='base.student')),
            ],
            options={
                'unique_together': {('student', 'is_primary')},
            },
        ),
        migrations.CreateModel(
            name='HostelAllocation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hostel_allocations', to='base.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hostel_allocations', to='base.student')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='base.room')),
            ],
            options={
                'unique_together': {('student', 'session')},
            },
        ),
    ]
