# Generated by Django 6.0.6 on 2026-07-16 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationwindow',
            options={'ordering': ['-opens_date']},
        ),
        migrations.AddField(
            model_name='registrationwindow',
            name='is_active',
            field=models.BooleanField(
                default=True, help_text='Manual kill-switch to close a window early regardless of dates.'),
        ),
        migrations.AddField(
            model_name='registrationwindow',
            name='late_closes_date',
            field=models.DateField(
                blank=True, help_text='Optional grace/late period end date, if late registration is allowed (often with a penalty fee).', null=True),
        ),
        migrations.AddField(
            model_name='registrationwindow',
            name='programme',
            field=models.ForeignKey(blank=True, help_text='Optional: restrict this window to one program. Leave blank for institution-wide.',
                                    null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_windows', to='base.programme'),
        ),
        migrations.AddField(
            model_name='registrationwindow',
            name='window_type',
            field=models.CharField(choices=[('course_registration', 'Course Registration'), ('bursary', 'Bursary/Financial Aid Registration'), ('hostel', 'Hostel Allocation'), ('exam_registration', 'Exam Registration'), ('backlog_exam', 'Backlog/Supplementary Exam Registration'),
                                   ('graduation_candidacy', 'Graduation Candidacy Nomination'), ('club_membership', 'Club Membership Drive'), ('scholarship', 'Scholarship Application')], default=None, help_text='What this window governs, e.g. course registration, bursary', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='registration_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='registration_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrationwindow',
            name='session',
            field=models.ForeignKey(help_text='e.g. Semester 2 2026/2027', on_delete=django.db.models.deletion.CASCADE,
                                    related_name='registration_windows', to='base.session'),
        ),
        migrations.AddConstraint(
            model_name='registrationwindow',
            constraint=models.UniqueConstraint(fields=(
                'session', 'window_type', 'programme'), name='unique_window_per_session_type_program'),
        ),
    ]
