# Generated by Django 6.0.8 on 2026-09-17 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_idcard_expiry_date_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='challenged_enrollment',
            field=models.ForeignKey(blank=True, help_text='The unit registration this grievance concerns.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='base.enrollment'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='challenged_result',
            field=models.ForeignKey(blank=True, help_text='Optional: the specific CAT/Exam row disputed, when the student is challenging one component rather than the unit total.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='base.result'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='result_action',
            field=models.CharField(blank=True, choices=[('challenge', 'Challenge Result / Grade Appeal'), ('resit', 'Request Resit / Supplementary'), ('missing', 'Missing or Unpublished Marks')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='snapshot_cat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='snapshot_exam',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='snapshot_grade',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='complaint',
            name='snapshot_taken_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='snapshot_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='historicalcomplaint',
            name='challenged_enrollment',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The unit registration this grievance concerns.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.enrollment'),
        ),
        migrations.AddField(
            model_name='historicalcomplaint',
            name='challenged_result',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Optional: the specific CAT/Exam row disputed, when the student is challenging one component rather than the unit total.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.result'),
        ),
        migrations.AddField(
            model_name='historicalcomplaint',
            name='result_action',
            field=models.CharField(blank=True, choices=[('challenge', 'Challenge Result / Grade Appeal'), ('resit', 'Request Resit / Supplementary'), ('missing', 'Missing or Unpublished Marks')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalcomplaint',
            name='snapshot_cat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='historicalcomplaint',
            name='snapshot_exam',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='historicalcomplaint',
            name='snapshot_grade',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='historicalcomplaint',
            name='snapshot_taken_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcomplaint',
            name='snapshot_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('Academic', 'Academic (Missing Marks, Exam Appeals, Lecturer Issues)'), ('Results', 'Results Dispute (Grade Challenge, Resit Request)'), ('Harassment', 'Harassment / Gender-Based Violence (Strict Confidentiality)'), ('Administrative', 'Administrative (Finance Portal, Admissions, Registration)'), ('Facilities', 'Facilities & Accommodation (Hostel Damage, Wi-Fi, Water)'), ('Catering', 'Catering & Health Services (Mess issues, Sick Bay complaints)'), ('Other', 'General / Unclassified Grievance')], max_length=45),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='address',
            field=models.CharField(blank=True, max_length=78, null=True),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='email',
            field=models.CharField(blank=True, max_length=78, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcomplaint',
            name='category',
            field=models.CharField(choices=[('Academic', 'Academic (Missing Marks, Exam Appeals, Lecturer Issues)'), ('Results', 'Results Dispute (Grade Challenge, Resit Request)'), ('Harassment', 'Harassment / Gender-Based Violence (Strict Confidentiality)'), ('Administrative', 'Administrative (Finance Portal, Admissions, Registration)'), ('Facilities', 'Facilities & Accommodation (Hostel Damage, Wi-Fi, Water)'), ('Catering', 'Catering & Health Services (Mess issues, Sick Bay complaints)'), ('Other', 'General / Unclassified Grievance')], max_length=45),
        ),
    ]
