# Generated by Django 6.0.8 on 2026-09-17 06:04

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_complaint_challenged_enrollment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('Academic', 'Academic ( Lecturer Issues)'), ('Results', 'Results Dispute (Grade Challenge,)'), ('Harassment', 'Harassment / Gender-Based Violence (Strict Confidentiality)'), ('Administrative', 'Administrative (Finance Portal, Admissions, Registration)'), ('Facilities', 'Facilities & Accommodation (Hostel Damage, Wi-Fi, Water)'), ('Catering', 'Catering & Health Services (Mess issues, Sick Bay complaints)'), ('Other', 'General / Unclassified Grievance')], max_length=45),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='result_action',
            field=models.CharField(blank=True, choices=[('challenge', 'Challenge Result / Grade Appeal')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcomplaint',
            name='category',
            field=models.CharField(choices=[('Academic', 'Academic ( Lecturer Issues)'), ('Results', 'Results Dispute (Grade Challenge,)'), ('Harassment', 'Harassment / Gender-Based Violence (Strict Confidentiality)'), ('Administrative', 'Administrative (Finance Portal, Admissions, Registration)'), ('Facilities', 'Facilities & Accommodation (Hostel Damage, Wi-Fi, Water)'), ('Catering', 'Catering & Health Services (Mess issues, Sick Bay complaints)'), ('Other', 'General / Unclassified Grievance')], max_length=45),
        ),
        migrations.AlterField(
            model_name='historicalcomplaint',
            name='result_action',
            field=models.CharField(blank=True, choices=[('challenge', 'Challenge Result / Grade Appeal')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='AcademicRequisition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('resit', 'Resit Examination'), ('supplementary', 'Supplementary Examination'), ('missing_marks', 'Missing / Unpublished Marks Investigation'), ('special_exam', 'Special Sit-in Exam (Missed for Valid Reason)')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('hod_approved', 'Recommended by HOD — Awaiting Registrar'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('reason', models.TextField(help_text="Why you're requesting this.")),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('hod_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('hod_remarks', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('registrar_remarks', models.TextField(blank=True, null=True)),
                ('fee_required', models.BooleanField(default=True)),
                ('fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fee_paid', models.BooleanField(default=False)),
                ('fee_paid_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_time_slot', models.CharField(blank=True, help_text='e.g. "08:00-11:00"', max_length=20, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requisitions', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(help_text='The unit registration this request concerns.', on_delete=django.db.models.deletion.PROTECT, related_name='requisitions', to='base.enrollment')),
                ('hod_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_reviewed_requisitions', to=settings.AUTH_USER_MODEL)),
                ('scheduled_venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.venue')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisitions', to='base.student')),
            ],
            options={
                'verbose_name': 'Academic Requisition',
                'verbose_name_plural': 'Academic Requisitions',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAcademicRequisition',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('record_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('deleted', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('resit', 'Resit Examination'), ('supplementary', 'Supplementary Examination'), ('missing_marks', 'Missing / Unpublished Marks Investigation'), ('special_exam', 'Special Sit-in Exam (Missed for Valid Reason)')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('hod_approved', 'Recommended by HOD — Awaiting Registrar'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('reason', models.TextField(help_text="Why you're requesting this.")),
                ('requested_at', models.DateTimeField(blank=True, editable=False)),
                ('hod_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('hod_remarks', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('registrar_remarks', models.TextField(blank=True, null=True)),
                ('fee_required', models.BooleanField(default=True)),
                ('fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fee_paid', models.BooleanField(default=False)),
                ('fee_paid_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_time_slot', models.CharField(blank=True, help_text='e.g. "08:00-11:00"', max_length=20, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(blank=True, db_constraint=False, help_text='The unit registration this request concerns.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.enrollment')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hod_reviewed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('scheduled_venue', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.venue')),
                ('student', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.student')),
            ],
            options={
                'verbose_name': 'historical Academic Requisition',
                'verbose_name_plural': 'historical Academic Requisitions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RequisitionDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to='requisitions/%Y/%m/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='base.academicrequisition')),
                ('uploaded_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_requisition_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
