# Generated by Django 6.0.6 on 2026-07-16 21:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_result_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='capacity',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='graduation',
            name='status',
            field=models.CharField(choices=[('nominated', 'Nominated'), ('verified', 'Verified'), ('approved', 'Approved'), ('conferred', 'Conferred')], default='nominated', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalcurriculum',
            name='capacity',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='programme',
            name='total_credits_required',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('dropped', 'Dropped'), ('completed', 'Completed')], default='pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='graduation',
            name='Tclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='graduation_candidates', to='base.tclass'),
        ),
        migrations.AlterField(
            model_name='graduation',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='graduation_candidacy', to='base.student'),
        ),
        migrations.AlterField(
            model_name='historicalenrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('dropped', 'Dropped'), ('completed', 'Completed')], default='pending', max_length=25),
        ),
        migrations.CreateModel(
            name='Convocation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('candidates', models.ManyToManyField(blank=True, related_name='convocations', to='base.graduation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DegreeAudit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credits_completed', models.PositiveIntegerField(default=0)),
                ('credits_remaining', models.PositiveIntegerField(default=0)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('result', models.CharField(choices=[('on_track', 'On Track'), ('deficient', 'Deficient'), ('eligible', 'Eligible for Graduation')], default='on_track', max_length=20)),
                ('last_reviewed', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='degree_audit', to='base.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diploma_number', models.CharField(max_length=50, unique=True)),
                ('conferred_date', models.DateField()),
                ('issued', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='registrar/diplomas/')),
                ('candidacy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diploma', to='base.graduation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IDCard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_number', models.CharField(max_length=30, unique=True)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='registrar/id_photos/')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='id_card', to='base.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatusChangeRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('leave', 'Leave of Absence'), ('withdrawal', 'Withdrawal'), ('readmission', 'Readmission'), ('program_transfer', 'Program Transfer')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='registrar/status_changes/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes_processed', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_change_requests', to='base.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
