# Generated by Django 6.0.6 on 2026-06-15 21:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_hostelallocation_move_in_date_hostelallocation_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsession',
            name='exam_type',
            field=models.CharField(choices=[('CAT', 'CAT'), ('MAIN', 'Main Exam'), ('SUPP', 'Supplementary'), ('SPECIAL', 'Special / Supplementary'), ('PRACTICAL', 'Practical')], max_length=10),
        ),
        migrations.CreateModel(
            name='ExamCard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('last_printed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_cards', to='base.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_cards', to='base.student')),
            ],
            options={
                'ordering': ['-issued_at'],
                'unique_together': {('student', 'session', 'is_active')},
            },
        ),
    ]
