# Generated by Django 6.0.6 on 2026-06-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_examsession_exam_type_examcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tclass',
            name='graduated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
