# Generated by Django 6.0.5 on 2026-06-03 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_financestaff_historicalcurriculum_itstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelwarden',
            name='hostel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.hostel'),
        ),
    ]
