# Generated by Django 6.0.8 on 2026-09-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_complaint_category_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examcard',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='examcard',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('student', 'session'), name='unique_active_examcard_per_student_session'),
        ),
    ]
