# Generated by Django 6.0.8 on 2026-09-19 22:22

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_examcard_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grievanceupdate',
            name='grievance',
        ),
        migrations.RemoveField(
            model_name='grievanceupdate',
            name='author',
        ),
        migrations.RemoveField(
            model_name='historicalgrievance',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='historicalgrievance',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalgrievance',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='historicalgrievance',
            name='term',
        ),
        migrations.AddField(
            model_name='curriculum',
            name='pass_mark',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum score to pass this specific course. Override per course — e.g. a professional/regulated unit might require 50.', null=True),
        ),
        migrations.AddField(
            model_name='historicalcurriculum',
            name='pass_mark',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum score to pass this specific course. Override per course — e.g. a professional/regulated unit might require 50.', null=True),
        ),
        migrations.AddField(
            model_name='hostelallocation',
            name='checked_out_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostelallocation',
            name='checked_out_by',
            field=models.ForeignKey(blank=True, help_text='The specific staff user account (Warden/Housekeeper) who manually Checked out  this Student.', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lecturerassignment',
            name='Tclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.curriculumclass'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='graduation',
            name='final_classification',
            field=models.CharField(choices=[('First_Class', 'First Class Honours / Distinction'), ('Second_Upper', 'Second Class Honours (Upper Division)'), ('Second_Lower', 'Second Class Honours (Lower Division)'), ('Pass', 'Pass (Standard Undergraduate or Postgraduate award)'), ('Satisfied', 'Satisfied ( Doctorates/PhDs)')], help_text='Official degree classification mapped to CUE data guidelines.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgraduation',
            name='final_classification',
            field=models.CharField(choices=[('First_Class', 'First Class Honours / Distinction'), ('Second_Upper', 'Second Class Honours (Upper Division)'), ('Second_Lower', 'Second Class Honours (Lower Division)'), ('Pass', 'Pass (Standard Undergraduate or Postgraduate award)'), ('Satisfied', 'Satisfied ( Doctorates/PhDs)')], help_text='Official degree classification mapped to CUE data guidelines.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Suspended', 'Suspended'), ('Review', 'Under Review'), ('Proposed', 'Proposed')], default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_entered',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='day_ones', to='base.tclass'),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_list', to='base.tclass'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stay',
            field=models.CharField(choices=[('resident', 'Resident'), ('outside', 'Non-Resident')], default='resident', max_length=78),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='year_introduced',
            field=models.CharField(blank=True, help_text='Academic year this entry was approved/introduced into the programme', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='weightingcomponent',
            name='aggregation',
            field=models.CharField(choices=[('average_all', 'Average all submissions'), ('best_n', 'Average the best N submissions'), ('sum', 'Sum all submissions'), ('latest', 'Most recent submission only'), ('latest_n', 'Most recent N Submissions only')], default='average_all', help_text="How multiple results of this type combine into this component's score. e.g. three CATs: average all three, or drop the worst and average the best 2.", max_length=15),
        ),
        migrations.CreateModel(
            name='HistoricalProgramme',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('record_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('deleted', models.BooleanField(default=False)),
                ('code', models.CharField(db_index=True, max_length=20)),
                ('programme_name', models.CharField(db_index=True, max_length=255)),
                ('level', models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate'), ('Diploma', 'Diploma'), ('Certificate', 'Certificate')], default='Undergraduate', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Suspended', 'Suspended'), ('Review', 'Under Review'), ('Proposed', 'Proposed')], default='Active', max_length=10)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('degree_type', models.CharField(choices=[('BSc', 'Bachelor of Science'), ('BEd', 'Bachelor of Education'), ('LLB', 'Bachelor of Laws'), ('BA', 'Bachelor of Arts'), ('BCom', 'Bachelor of Commerce'), ('BBIT', 'Bachelor of Business Information Technology'), ('B.Arch', 'Bachelor of Architecture'), ('BEng', 'Bachelor of Engineering'), ('MBChB', 'Bachelor of Medicine and Bachelor of Surgery'), ('BPharm', 'Bachelor of Pharmacy'), ('BDS', 'Bachelor of Dental Surgery'), ('PGDE', 'Post Graduate Diploma in Education'), ('MSc', 'Master of Science'), ('MA', 'Master of Arts'), ('MBA', 'Master of Business Administration'), ('LLM', 'Master of Laws'), ('MEd', 'Master of Education'), ('MPH', 'Master of Public Health'), ('PhD', 'Doctor of Philosophy'), ('MD', 'Doctor of Medicine')], max_length=123)),
                ('capacity', models.IntegerField(default=70)),
                ('unesco_isced', models.CharField(blank=True, choices=[('0011', 'Basic programmes and qualifications'), ('0021', 'Literacy and numeracy'), ('0031', 'Personal skills and development'), ('0099', 'Generic programmes and qualifications not elsewhere classified'), ('0111', 'Education science'), ('0112', 'Training for pre-school teachers'), ('0113', 'Teacher training without subject specialisation'), ('0114', 'Teacher training with subject specialisation'), ('0188', 'Inter-disciplinary programmes involving education'), ('0211', 'Audio-visual techniques and media production'), ('0212', 'Fashion, interior and industrial design'), ('0213', 'Fine arts'), ('0214', 'Handicrafts'), ('0215', 'Music and performing arts'), ('0221', 'Religion and theology'), ('0222', 'History and archaeology'), ('0223', 'Philosophy and ethics'), ('0231', 'Language acquisition'), ('0232', 'Literature and linguistics'), ('0288', 'Inter-disciplinary programmes involving arts and humanities'), ('0311', 'Economics'), ('0312', 'Political sciences and civics'), ('0313', 'Psychology'), ('0314', 'Sociology and cultural studies'), ('0321', 'Journalism and reporting'), ('0322', 'Library, information and archival studies'), ('0388', 'Inter-disciplinary programmes involving social sciences/journalism'), ('0411', 'Accounting and taxation'), ('0412', 'Finance, banking and insurance'), ('0413', 'Management and administration'), ('0414', 'Marketing and advertising'), ('0415', 'Secretarial and office work'), ('0416', 'Wholesale and retail sales'), ('0417', 'Work skills'), ('0421', 'Law'), ('0488', 'Inter-disciplinary programmes involving business/admin/law'), ('0511', 'Biology'), ('0512', 'Biochemistry'), ('0521', 'Environmental sciences'), ('0522', 'Natural environments and wildlife'), ('0531', 'Chemistry'), ('0532', 'Earth sciences'), ('0533', 'Physics'), ('0541', 'Mathematics'), ('0542', 'Statistics'), ('0588', 'Inter-disciplinary programmes involving natural sciences/maths'), ('0611', 'Computer use (Basic IT/Applications)'), ('0612', 'Database and network design and administration'), ('0613', 'Software and applications development and analysis (Computer Science)'), ('0688', 'Inter-disciplinary programmes involving ICTs'), ('0711', 'Chemical engineering and processes'), ('0712', 'Environmental protection technology'), ('0713', 'Electricity and energy'), ('0714', 'Electronics and automation (Mechatronics/Hardware Engineering)'), ('0715', 'Mechanics and metal trades'), ('0716', 'Motor vehicles, ships and aircraft (Aeronautical/Automotive)'), ('0721', 'Food processing'), ('0722', 'Materials (glass, paper, plastic and wood)'), ('0723', 'Textiles (clothes, footwear and leather)'), ('0724', 'Mining and extraction'), ('0731', 'Architecture and town planning'), ('0732', 'Building and civil engineering'), ('0788', 'Inter-disciplinary programmes involving engineering/construction'), ('0811', 'Crop and livestock production'), ('0812', 'Horticulture'), ('0821', 'Forestry'), ('0831', 'Fisheries'), ('0841', 'Veterinary'), ('0888', 'Inter-disciplinary programmes involving agriculture/veterinary'), ('0911', 'Dental studies'), ('0912', 'Medicine (Clinical Medicine/Surgery/MBChB)'), ('0913', 'Nursing and midwifery'), ('0914', 'Medical diagnostic and treatment technology (Radiology/Lab Tech)'), ('0915', 'Therapy and rehabilitation (Physiotherapy)'), ('0916', 'Pharmacy'), ('0917', 'Traditional and complementary medicine and therapy'), ('0921', 'Care of elderly and of disabled adults'), ('0922', 'Child care and youth services'), ('0923', 'Social work and counselling'), ('0988', 'Inter-disciplinary programmes involving health and welfare'), ('1011', 'Domestic services'), ('1012', 'Hair and beauty services'), ('1013', 'Hotel, restaurants and catering'), ('1014', 'Sports'), ('1015', 'Travel, tourism and leisure'), ('1021', 'Community sanitation'), ('1022', 'Occupational health and safety'), ('1031', 'Military science and defence'), ('1032', 'Protection of persons and property (Security Management/Police)'), ('1041', 'Transport services (Logistics/Aviation operations)'), ('1088', 'Inter-disciplinary programmes involving services')], help_text='Standardized UNESCO tag for this specific subject matter.', max_length=123, null=True)),
                ('kuccps_programme_code', models.CharField(blank=True, db_index=True, max_length=7, null=True)),
                ('duration_years', models.IntegerField(default=4)),
                ('semesters_per_year', models.IntegerField(default=2)),
                ('total_credits_required', models.PositiveIntegerField(default=120)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('current_class', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.tclass')),
                ('department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.department')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical programme',
                'verbose_name_plural': 'historical programmes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.DeleteModel(
            name='Grievance',
        ),
        migrations.DeleteModel(
            name='GrievanceUpdate',
        ),
        migrations.DeleteModel(
            name='HistoricalGrievance',
        ),
    ]
