# Generated by Django 6.0.5 on 2026-06-04 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_hostelwarden_hostel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='deffered',
            new_name='deferred',
        ),
    ]
