# Generated by Django 6.0.6 on 2026-06-17 18:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_tclass_graduated'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelListing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('badge', models.CharField(blank=True, choices=[('popular', '⭐ Popular'), ('students', '👩\u200d🎓 Students only'), ('scenic', '🏞️ Scenic'), ('community', '🤝 Community'), ('views', '🌅 Great views'), ('other', 'Other')], max_length=20, null=True)),
                ('location', models.CharField(help_text='Street address and landmark', max_length=255)),
                ('distance_note', models.CharField(help_text='e.g. 2 min walk to North Gate', max_length=120)),
                ('price_per_month', models.PositiveIntegerField(help_text='KES per month')),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('single_ensuite', 'Single en-suite'), ('shared_2', '2–4 sharing'), ('shared_4', '4–6 sharing'), ('studio', 'Studio & shared'), ('mixed', 'Single & shared')], max_length=20)),
                ('has_wifi', models.BooleanField(default=True)),
                ('has_meals', models.BooleanField(default=False)),
                ('has_laundry', models.BooleanField(default=False)),
                ('has_gym', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_kitchen', models.BooleanField(default=False)),
                ('has_study_rooms', models.BooleanField(default=False)),
                ('has_lounge', models.BooleanField(default=False)),
                ('has_bike_storage', models.BooleanField(default=False)),
                ('has_ethernet', models.BooleanField(default=False)),
                ('wifi_note', models.CharField(blank=True, help_text='e.g. High-speed, WiFi + study rooms', max_length=60)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower = appears first')),
            ],
            options={
                'ordering': ['sort_order', 'price_per_month'],
            },
        ),
    ]
