# Generated by Django 6.0.6 on 2026-06-18 09:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_hostellisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='deferment',
            name='request_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='historicaldeferment',
            name='request_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='deferment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_deferments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deferment',
            name='reason_detail',
            field=models.TextField(blank=True, help_text='Free text from student or registrar', null=True),
        ),
        migrations.AlterField(
            model_name='historicaldeferment',
            name='reason_detail',
            field=models.TextField(blank=True, help_text='Free text from student or registrar', null=True),
        ),
        migrations.CreateModel(
            name='DefermentDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='deferments/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('deferment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='base.deferment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
