# Generated by Django 6.0.5 on 2026-06-04 08:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_deffered_student_deferred'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonUnitCurriculum',
            fields=[
            ],
            options={
                'verbose_name': 'Common Unit',
                'verbose_name_plural': 'Common Units',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.curriculum',),
        ),
        migrations.CreateModel(
            name='GraduatedStudent',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Graduated Students',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.student',),
        ),
        migrations.AlterModelOptions(
            name='deferredstudent',
            options={'verbose_name_plural': 'Deferred Students'},
        ),
        migrations.AlterModelOptions(
            name='residentstudent',
            options={'verbose_name_plural': 'Resident Students'},
        ),
        migrations.CreateModel(
            name='CourseEvaluation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=0)),
                ('comments', models.TextField(blank=True, null=True)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.curriculum')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LecturerEvaluation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=0)),
                ('comments', models.TextField(blank=True, null=True)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.curriculum')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.lecturer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
