# Generated by Django 6.0.6 on 2026-07-17 11:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_application_applicationdocument_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('scope', models.CharField(choices=[('class', 'Specific class'), ('curriculum', 'Specific unit'), ('dept', 'Whole department')], max_length=15)),
                ('is_urgent', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('curriculum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.curriculum')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnnouncementDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='lecturer_announcements/%Y/%m/')),
                ('description', models.CharField(blank=True, help_text='e.g. Lecture slides, assignment brief', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in the portal attachment list')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='base.announcement')),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
