# Generated by Django 6.0.8 on 2026-09-20 08:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_department_address_department_alternate_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7 to 15 digits, optionally starting with +).', regex='^\\+?[0-9]{7,15}$')])),
                ('alternate_phone_number', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7 to 15 digits, optionally starting with +).', regex='^\\+?[0-9]{7,15}$')])),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('institution_name', models.CharField(max_length=123)),
                ('logo', models.ImageField(upload_to='logo/')),
                ('charter_number', models.CharField(blank=True, max_length=100, null=True)),
                ('active_session', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.session')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7 to 15 digits, optionally starting with +).', regex='^\\+?[0-9]{7,15}$')])),
                ('alternate_phone_number', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7 to 15 digits, optionally starting with +).', regex='^\\+?[0-9]{7,15}$')])),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('office_name', models.CharField(max_length=123)),
                ('office_type', models.CharField(choices=[('admissions', 'Admissions'), ('student_support', 'Student Support'), ('registrar', 'Registrar'), ('bursar', 'Bursar / Finance'), ('it_helpdesk', 'IT Helpdesk'), ('library', 'Library'), ('hr', 'Human Resources'), ('other', 'Other')], default='other', max_length=30)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='base.institution')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
