# Generated by Django 6.0.6 on 2026-08-07 07:37

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_announcement_announcementdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralStaff',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_number', models.CharField(max_length=20, unique=True)),
                ('employment_type', models.CharField(choices=[('tenured', 'Tenured / Permanent (Full-Time)'), ('probationary', 'Probationary / Tenure-Track'), ('contract_ft', 'Contract (Full-Time)'), ('contract_pt', 'Contract (Part-Time)'), ('casual', 'Casual / Day Labourer'), ('adjunct', 'Adjunct Faculty'), ('visiting', 'Visiting Scholar / Faculty'), ('sabbatical', 'Sabbatical Placement'), ('honorary', 'Honorary / Guest Appointment'), ('emeritus', 'Emeritus / Retired Active'), ('grant_funded', 'Grant-Funded / Project-Specific'), ('postdoc', 'Postdoctoral Fellowship'), ('work_study', 'Student Work-Study Program'), ('graduate_assistant', 'Graduate Assistantship'), ('secondment', 'Secondment / On Loan'), ('outsourced', 'Outsourced Third-Party Contractor')], default='contract_ft', max_length=20)),
                ('staff_category', models.CharField(choices=[('academic', 'Academic (Teaching & Research)'), ('teaching_only', 'Teaching Only / Instructional'), ('research_only', 'Research Only'), ('admin_academic', 'Admin & Academic (e.g., Dean, HOD)'), ('executive', 'Executive Leadership (e.g., VC, Registrar)'), ('admin_support', 'General Administrative Support'), ('finance_hr', 'Finance, HR, & Procurement'), ('it_technical', 'IT & Technical Support'), ('lab_technical', 'Laboratory & Workshop Technical'), ('facilities_maintenance', 'Facilities, Maintenance, & Estates'), ('security', 'Campus Security & Safety'), ('student_affairs', 'Student Affairs & Residence Life'), ('health_medical', 'Campus Health & Medical Services'), ('library', 'Library & Information Services'), ('hospitality_catering', 'Hospitality, Catering, & Retail')], default='academic', max_length=30)),
                ('date_joined', models.DateField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('personal_email', models.EmailField(blank=True, help_text='Non-institutional email — optional', max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('alternative_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('office_location', models.CharField(blank=True, help_text='e.g. Room 302, CS Building', max_length=100, null=True)),
                ('office_hours', models.CharField(blank=True, help_text='e.g. Mon & Wed 14:00 – 16:00', max_length=100, null=True)),
                ('contract_start_date', models.DateField(blank=True, help_text='Mandatory for contract-based employment types.', null=True)),
                ('contract_end_date', models.DateField(blank=True, help_text='The date this contract expires. Mandatory for contract types.', null=True)),
                ('grant_number', models.CharField(blank=True, help_text='The funding grant reference code. Mandatory if status is Grant-Funded.', max_length=100, null=True)),
                ('grant_expiry_date', models.DateField(blank=True, help_text='The date when external grant funding for this position expires.', null=True)),
                ('role', models.CharField(choices=[('secretary', 'Departmental / School Secretary'), ('office_assistant', 'Office Assistant'), ('clerk', 'Clerk'), ('driver', 'Driver'), ('groundskeeper', 'Groundskeeper / Facilities'), ('other', 'Other General Staff')], default='other', max_length=30)),
            ],
            options={
                'verbose_name': 'General Staff',
                'verbose_name_plural': 'General Staff',
            },
        ),
        migrations.CreateModel(
            name='HistoricalGeneralStaff',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('record_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('staff_number', models.CharField(db_index=True, max_length=20)),
                ('employment_type', models.CharField(choices=[('tenured', 'Tenured / Permanent (Full-Time)'), ('probationary', 'Probationary / Tenure-Track'), ('contract_ft', 'Contract (Full-Time)'), ('contract_pt', 'Contract (Part-Time)'), ('casual', 'Casual / Day Labourer'), ('adjunct', 'Adjunct Faculty'), ('visiting', 'Visiting Scholar / Faculty'), ('sabbatical', 'Sabbatical Placement'), ('honorary', 'Honorary / Guest Appointment'), ('emeritus', 'Emeritus / Retired Active'), ('grant_funded', 'Grant-Funded / Project-Specific'), ('postdoc', 'Postdoctoral Fellowship'), ('work_study', 'Student Work-Study Program'), ('graduate_assistant', 'Graduate Assistantship'), ('secondment', 'Secondment / On Loan'), ('outsourced', 'Outsourced Third-Party Contractor')], default='contract_ft', max_length=20)),
                ('staff_category', models.CharField(choices=[('academic', 'Academic (Teaching & Research)'), ('teaching_only', 'Teaching Only / Instructional'), ('research_only', 'Research Only'), ('admin_academic', 'Admin & Academic (e.g., Dean, HOD)'), ('executive', 'Executive Leadership (e.g., VC, Registrar)'), ('admin_support', 'General Administrative Support'), ('finance_hr', 'Finance, HR, & Procurement'), ('it_technical', 'IT & Technical Support'), ('lab_technical', 'Laboratory & Workshop Technical'), ('facilities_maintenance', 'Facilities, Maintenance, & Estates'), ('security', 'Campus Security & Safety'), ('student_affairs', 'Student Affairs & Residence Life'), ('health_medical', 'Campus Health & Medical Services'), ('library', 'Library & Information Services'), ('hospitality_catering', 'Hospitality, Catering, & Retail')], default='academic', max_length=30)),
                ('date_joined', models.DateField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('personal_email', models.EmailField(blank=True, help_text='Non-institutional email — optional', max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('alternative_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('office_location', models.CharField(blank=True, help_text='e.g. Room 302, CS Building', max_length=100, null=True)),
                ('office_hours', models.CharField(blank=True, help_text='e.g. Mon & Wed 14:00 – 16:00', max_length=100, null=True)),
                ('contract_start_date', models.DateField(blank=True, help_text='Mandatory for contract-based employment types.', null=True)),
                ('contract_end_date', models.DateField(blank=True, help_text='The date this contract expires. Mandatory for contract types.', null=True)),
                ('grant_number', models.CharField(blank=True, help_text='The funding grant reference code. Mandatory if status is Grant-Funded.', max_length=100, null=True)),
                ('grant_expiry_date', models.DateField(blank=True, help_text='The date when external grant funding for this position expires.', null=True)),
                ('role', models.CharField(choices=[('secretary', 'Departmental / School Secretary'), ('office_assistant', 'Office Assistant'), ('clerk', 'Clerk'), ('driver', 'Driver'), ('groundskeeper', 'Groundskeeper / Facilities'), ('other', 'Other General Staff')], default='other', max_length=30)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical General Staff',
                'verbose_name_plural': 'historical General Staff',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveConstraint(
            model_name='academicappointment',
            name='unique_active_appointment_per_scope',
        ),
        migrations.AddField(
            model_name='administrativestaff',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrative_appointments', to='base.lecturer'),
        ),
        migrations.AddField(
            model_name='building',
            name='is_exam_venue',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='idcard',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='registrar/id_file'),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='tenured',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='current_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.tclass'),
        ),
        migrations.AddField(
            model_name='tclass',
            name='liason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.lecturer'),
        ),
        migrations.AlterField(
            model_name='academicappointment',
            name='appointment_type',
            field=models.CharField(choices=[('hod', 'Head of Department'), ('dean', 'Dean of Faculty'), ('director', 'Director of School'), ('exams_coordinator', 'Departmental Exams Coordinator')], max_length=20),
        ),
        migrations.AlterField(
            model_name='administrativestaff',
            name='role',
            field=models.CharField(choices=[('vc', 'Vice-Chancellor / President'), ('dvc', 'Deputy Vice-Chancellor'), ('registrar', 'University Registrar'), ('director_of_exams', 'Director of Examinations'), ('dept_admin', 'Department Administrator'), ('school_admin', 'School / Faculty Administrator'), ('institution_admin', 'Central Institution Administrator'), ('executive_sec', 'Executive Secretary / Admin Assistant'), ('general_staff', 'General Administrative Staff')], default='general_staff', max_length=30),
        ),
        migrations.AlterField(
            model_name='administrativestaff',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='councilterm',
            name='theme',
            field=models.CharField(blank=True, default='Headless Chicken', help_text="This council's manifesto theme/slogan, if any.", max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='practical_hours_per_week',
            field=models.PositiveIntegerField(default=0, help_text='Required if course_type is (Practical/Lab).'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='time_slot',
            field=models.CharField(choices=[('08:00-11:00', '1st Slot (08:00 – 11:00)'), ('11:00-14:00', '2nd Slot (11:00 – 14:00)'), ('14:00-17:00', '3rd Slot (14:00 – 17:00)'), ('17:00-20:00', '4th Slot (17:00 – 20:00)'), ('20:00-23:00', '5th Slot (20:00 – 23:00)')], max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcouncilterm',
            name='theme',
            field=models.CharField(blank=True, default='Headless Chicken', help_text="This council's manifesto theme/slogan, if any.", max_length=255),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='role',
            field=models.CharField(choices=[('lecturer', 'Lecturer'), ('hod', 'Head of Department'), ('dean', 'Dean of Faculty'), ('director', 'Director of School'), ('exams_coordinator', 'Departmental Exams Coordinator')], default='lecturer', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_entered',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_list', to='base.tclass'),
        ),
        migrations.AlterField(
            model_name='tclass',
            name='year_of_study',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='generalstaff',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='base.department'),
        ),
        migrations.AddField(
            model_name='generalstaff',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='base.school'),
        ),
        migrations.AddField(
            model_name='generalstaff',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Direct supervisor — must be an active campus staff member/admin.', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_subordinates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generalstaff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalgeneralstaff',
            name='department',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.department'),
        ),
        migrations.AddField(
            model_name='historicalgeneralstaff',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalgeneralstaff',
            name='school',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.school'),
        ),
        migrations.AddField(
            model_name='historicalgeneralstaff',
            name='supervisor',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Direct supervisor — must be an active campus staff member/admin.', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalgeneralstaff',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
