# Generated by Django 6.0.5 on 2026-06-07 09:30

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_commonunitcurriculum_graduatedstudent_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emergencycontact',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='initiated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 6, 7, 12, 30, 1, 424838), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='provider_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=15),
        ),
        migrations.AddField(
            model_name='payment',
            name='initiated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='relationship',
            field=models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian'), ('spouse', 'Spouse'), ('child', 'Child'), ('sibling', 'Sibling'), ('grandparent', 'Grandparent'), ('grandchild', 'Grandchild'), ('relative', 'Relative'), ('coworker', 'Coworker'), ('neighbor', 'Neighbor'), ('caregiver', 'Caregiver'), ('family-friend', 'Family Friend'), ('friend', 'Friend'), ('other', 'Other')], max_length=78),
        ),
        migrations.AlterField(
            model_name='historicalpayment',
            name='transaction_ref',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_ref',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='emergencycontact',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('student', 'is_primary'), name='unique_primary_contact_per_student'),
        ),
    ]
