# Generated by Django 6.0.6 on 2026-06-18 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_deferment_request_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseevaluation',
            name='curriculum',
        ),
        migrations.AddField(
            model_name='courseevaluation',
            name='enrollment',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='base.enrollment'),
            preserve_default=False,
        ),
    ]
