# Generated by Django 6.0.6 on 2026-08-07 12:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_generalstaff_historicalgeneralstaff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativestaff',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('on-leave', 'On Leave'), ('adjunct', 'Adjunct'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='financestaff',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('on-leave', 'On Leave'), ('adjunct', 'Adjunct'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='generalstaff',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('on-leave', 'On Leave'), ('adjunct', 'Adjunct'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalgeneralstaff',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('on-leave', 'On Leave'), ('adjunct', 'Adjunct'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='hostelwarden',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('on-leave', 'On Leave'), ('adjunct', 'Adjunct'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='itstaff',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('on-leave', 'On Leave'), ('adjunct', 'Adjunct'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='labtechnicalstaff',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('on-leave', 'On Leave'), ('adjunct', 'Adjunct'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('on-leave', 'On Leave'), ('adjunct', 'Adjunct'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='librarystaff',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('on-leave', 'On Leave'), ('adjunct', 'Adjunct'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='medicalstaff',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('on-leave', 'On Leave'), ('adjunct', 'Adjunct'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='administrativestaff',
            name='role',
            field=models.CharField(choices=[('vc', 'Vice-Chancellor / President'), ('dvc', 'Deputy Vice-Chancellor'), ('registrar', 'University Registrar'), ('director_of_exams', 'Director of Examinations'), ('hod', 'Head of Department'), ('dean', 'Dean of Faculty'), ('director', 'Director of School'), ('executive_sec', 'Executive Secretary / Admin Assistant'), ('general_staff', 'General Administrative Staff')], default='general_staff', max_length=30),
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('proposed', 'Proposed'), ('repealed', 'Repealed'), ('suspended', 'Suspended'), ('under-review', 'Under Review')], default='active', max_length=75)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.course')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.programme')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
