# Generated by Django 6.0.5 on 2026-06-08 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_emergencycontact_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='school',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_active',
        ),
    ]
