# Generated by Django 6.0.8 on 2026-09-20 11:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_institution_office'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyClassExecutionVenue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Daily Execution Class Venue Override',
            },
        ),
        migrations.CreateModel(
            name='TimetableClassVenue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Timetable Class Venue Override',
            },
        ),
        migrations.RemoveField(
            model_name='backlogregistration',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='backlogregistration',
            name='original_result',
        ),
        migrations.RemoveField(
            model_name='backlogregistration',
            name='student',
        ),
        migrations.RemoveField(
            model_name='revaluationrequest',
            name='result',
        ),
        migrations.RemoveField(
            model_name='revaluationrequest',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='revaluationrequest',
            name='student',
        ),
        migrations.AlterUniqueTogether(
            name='dailyclassexecution',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='lecturerassignment',
            name='Tclass',
        ),
        migrations.RemoveField(
            model_name='weightingcomponent',
            name='best_n_count',
        ),
        migrations.AddField(
            model_name='academicrequisition',
            name='attempt_number',
            field=models.PositiveSmallIntegerField(blank=True, default=2, help_text='Which attempt at this course this is (2nd, 3rd, ...). Used to enforce max-attempt policy and flag final attempts.', null=True),
        ),
        migrations.AddField(
            model_name='academicrequisition',
            name='disputed_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reevaluation_requisitions', to='base.result'),
        ),
        migrations.AddField(
            model_name='academicrequisition',
            name='exam_session',
            field=models.ForeignKey(blank=True, help_text='The exam sitting this resit/supplementary/special exam is registered for, once one exists. Distinct from scheduled_date/time_slot/venue, which cover ad-hoc scheduling before/instead of a formal ExamSession.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to='base.examsession'),
        ),
        migrations.AddField(
            model_name='academicrequisition',
            name='outcome_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisition_outcomes', to='base.result'),
        ),
        migrations.AddField(
            model_name='academicrequisition',
            name='revaluation_outcome',
            field=models.CharField(blank=True, choices=[('changed', 'Marks Changed'), ('unchanged', 'Marks Unchanged')], help_text="Only set for type='re_evaluation' on completion — whether the remark actually changed the score.", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='cap_supplementary_at_pass_mark',
            field=models.BooleanField(default=True, help_text="If true, a supplementary attempt's score is capped at the course pass mark for grading purposes — a supplementary pass never outscores a first-sitting pass. The raw score entered on Result is preserved for the record; only the value used in grading is capped."),
        ),
        migrations.AddField(
            model_name='dailyclassexecution',
            name='lecturer_assignment',
            field=models.ForeignKey(blank=True, help_text="Which lecturer (and, for a common unit, which class) this row tracks attendance for. Required explicitly only when the curriculum has more than one active LecturerAssignment — otherwise resolved automatically from the slot's single one.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_class_executions', to='base.lecturerassignment'),
        ),
        migrations.AddField(
            model_name='deferment',
            name='confirmation_document',
            field=models.FileField(blank=True, help_text="Generated printable PDF confirming the deferment, produced once request_status='approved'.", null=True, upload_to='deferments/confirmations/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='deferment',
            name='confirmation_reference',
            field=models.CharField(blank=True, help_text="Generated once approved, e.g. 'DEF-2026-000123'. Printed on the confirmation document as the official reference.", max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='deferment',
            name='review_remarks',
            field=models.TextField(blank=True, default='', help_text="HOD/registrar's response to the request — reason for rejection, or conditions attached to an approval."),
        ),
        migrations.AddField(
            model_name='deferment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deferment',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_deferments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalacademicrequisition',
            name='attempt_number',
            field=models.PositiveSmallIntegerField(blank=True, default=2, help_text='Which attempt at this course this is (2nd, 3rd, ...). Used to enforce max-attempt policy and flag final attempts.', null=True),
        ),
        migrations.AddField(
            model_name='historicalacademicrequisition',
            name='disputed_result',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.result'),
        ),
        migrations.AddField(
            model_name='historicalacademicrequisition',
            name='exam_session',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The exam sitting this resit/supplementary/special exam is registered for, once one exists. Distinct from scheduled_date/time_slot/venue, which cover ad-hoc scheduling before/instead of a formal ExamSession.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.examsession'),
        ),
        migrations.AddField(
            model_name='historicalacademicrequisition',
            name='outcome_result',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.result'),
        ),
        migrations.AddField(
            model_name='historicalacademicrequisition',
            name='revaluation_outcome',
            field=models.CharField(blank=True, choices=[('changed', 'Marks Changed'), ('unchanged', 'Marks Unchanged')], help_text="Only set for type='re_evaluation' on completion — whether the remark actually changed the score.", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='cap_supplementary_at_pass_mark',
            field=models.BooleanField(default=True, help_text="If true, a supplementary attempt's score is capped at the course pass mark for grading purposes — a supplementary pass never outscores a first-sitting pass. The raw score entered on Result is preserved for the record; only the value used in grading is capped."),
        ),
        migrations.AddField(
            model_name='historicaldeferment',
            name='confirmation_document',
            field=models.TextField(blank=True, help_text="Generated printable PDF confirming the deferment, produced once request_status='approved'.", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicaldeferment',
            name='confirmation_reference',
            field=models.CharField(blank=True, db_index=True, help_text="Generated once approved, e.g. 'DEF-2026-000123'. Printed on the confirmation document as the official reference.", max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicaldeferment',
            name='review_remarks',
            field=models.TextField(blank=True, default='', help_text="HOD/registrar's response to the request — reason for rejection, or conditions attached to an approval."),
        ),
        migrations.AddField(
            model_name='historicaldeferment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldeferment',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalresult',
            name='source',
            field=models.CharField(choices=[('original', 'Original Sitting'), ('resit', 'Resit'), ('supplementary', 'Supplementary'), ('special_exam', 'Special Sit-in Exam'), ('re_evaluation', 'Re-evaluation / Remark')], default='original', help_text='Why this Result row exists — an original sitting, or the outcome of an AcademicRequisition (resit/supplementary/special exam/re-evaluation). type stays the assessment component (CAT/Exam/etc.) either way, so weighting-scheme components keep working unchanged.', max_length=20),
        ),
        migrations.AddField(
            model_name='lecturerassignment',
            name='class_link',
            field=models.ForeignKey(blank=True, help_text='For a shared curriculum slot spanning several classes (e.g. a common unit), pin this assignment to one specific class rather than the whole slot. Used to filter result entry and class lists, and to compute per-class workload, when a curriculum has multiple classes attached.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lecturer_assignments', to='base.curriculumclass'),
        ),
        migrations.AddField(
            model_name='result',
            name='source',
            field=models.CharField(choices=[('original', 'Original Sitting'), ('resit', 'Resit'), ('supplementary', 'Supplementary'), ('special_exam', 'Special Sit-in Exam'), ('re_evaluation', 'Re-evaluation / Remark')], default='original', help_text='Why this Result row exists — an original sitting, or the outcome of an AcademicRequisition (resit/supplementary/special exam/re-evaluation). type stays the assessment component (CAT/Exam/etc.) either way, so weighting-scheme components keep working unchanged.', max_length=20),
        ),
        migrations.AddField(
            model_name='weightingcomponent',
            name='n_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Used by 'best_n' (top N scores) and 'latest_n' (most recent N submissions) — how many results to include, e.g. 2 (best/latest 2 of 3).", null=True),
        ),
        migrations.AlterField(
            model_name='academicrequisition',
            name='type',
            field=models.CharField(choices=[('resit', 'Resit Examination'), ('supplementary', 'Supplementary Examination'), ('missing_marks', 'Missing / Unpublished Marks Investigation'), ('special_exam', 'Special Sit-in Exam (Missed for Valid Reason)'), ('re_evaluation', 'Re-evaluation / Remarking')], max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='current_level',
            field=models.CharField(blank=True, choices=[('result_entrant', 'Result Entrant (Lecturer who recorded the score)'), ('lecturer_liaison', 'Programme Liaison (Lecturer, via Tclass.liason)'), ('Department', 'Department Level (HOD)'), ('school_rep', 'Student Council – School Representative'), ('School', 'School / Faculty Level (Dean)'), ('secretary_general', 'Student Council – Secretary General'), ('deputy_chairperson', 'Student Council – Deputy Chairperson'), ('chairperson', 'Student Council – Chairperson'), ('StudentAffairs', 'Dean of Students'), ('Division', 'Division Level (Registrar Academic Affairs)'), ('Senate', 'University Senate / Vice-Chancellor Executive'), ('External', 'External Body / Ombudsman / Legal Counsel')], help_text="Where in this category's escalation path the complaint currently sits. Set on first save, advanced by escalate().", max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='complaintescalationhistory',
            name='escalated_from_level',
            field=models.CharField(choices=[('result_entrant', 'Result Entrant (Lecturer who recorded the score)'), ('lecturer_liaison', 'Programme Liaison (Lecturer, via Tclass.liason)'), ('Department', 'Department Level (HOD)'), ('school_rep', 'Student Council – School Representative'), ('School', 'School / Faculty Level (Dean)'), ('secretary_general', 'Student Council – Secretary General'), ('deputy_chairperson', 'Student Council – Deputy Chairperson'), ('chairperson', 'Student Council – Chairperson'), ('StudentAffairs', 'Dean of Students'), ('Division', 'Division Level (Registrar Academic Affairs)'), ('Senate', 'University Senate / Vice-Chancellor Executive'), ('External', 'External Body / Ombudsman / Legal Counsel')], max_length=30),
        ),
        migrations.AlterField(
            model_name='complaintescalationhistory',
            name='escalated_to_level',
            field=models.CharField(choices=[('result_entrant', 'Result Entrant (Lecturer who recorded the score)'), ('lecturer_liaison', 'Programme Liaison (Lecturer, via Tclass.liason)'), ('Department', 'Department Level (HOD)'), ('school_rep', 'Student Council – School Representative'), ('School', 'School / Faculty Level (Dean)'), ('secretary_general', 'Student Council – Secretary General'), ('deputy_chairperson', 'Student Council – Deputy Chairperson'), ('chairperson', 'Student Council – Chairperson'), ('StudentAffairs', 'Dean of Students'), ('Division', 'Division Level (Registrar Academic Affairs)'), ('Senate', 'University Senate / Vice-Chancellor Executive'), ('External', 'External Body / Ombudsman / Legal Counsel')], max_length=30),
        ),
        migrations.AlterField(
            model_name='dailyclassexecution',
            name='class_representative',
            field=models.ForeignKey(blank=True, help_text='The Class Representative or student who signs off that the class took place.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_daily_classes', to='base.student'),
        ),
        migrations.AlterField(
            model_name='dailyclassexecution',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dailyclassexecution',
            name='reschedule_requested_by_role',
            field=models.CharField(blank=True, choices=[('LECTURER', 'Requested by Assigned Faculty/Lecturer'), ('STUDENT', 'Requested by Student Cohort / Class Rep'), ('ADMIN', 'Enforced by University Administration')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='dailyclassexecution',
            name='rescheduled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initiated_class_reschedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalacademicrequisition',
            name='type',
            field=models.CharField(choices=[('resit', 'Resit Examination'), ('supplementary', 'Supplementary Examination'), ('missing_marks', 'Missing / Unpublished Marks Investigation'), ('special_exam', 'Special Sit-in Exam (Missed for Valid Reason)'), ('re_evaluation', 'Re-evaluation / Remarking')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalcomplaint',
            name='current_level',
            field=models.CharField(blank=True, choices=[('result_entrant', 'Result Entrant (Lecturer who recorded the score)'), ('lecturer_liaison', 'Programme Liaison (Lecturer, via Tclass.liason)'), ('Department', 'Department Level (HOD)'), ('school_rep', 'Student Council – School Representative'), ('School', 'School / Faculty Level (Dean)'), ('secretary_general', 'Student Council – Secretary General'), ('deputy_chairperson', 'Student Council – Deputy Chairperson'), ('chairperson', 'Student Council – Chairperson'), ('StudentAffairs', 'Dean of Students'), ('Division', 'Division Level (Registrar Academic Affairs)'), ('Senate', 'University Senate / Vice-Chancellor Executive'), ('External', 'External Body / Ombudsman / Legal Counsel')], help_text="Where in this category's escalation path the complaint currently sits. Set on first save, advanced by escalate().", max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='venue',
            field=models.ForeignKey(help_text='Default venue for this slot. For a shared curriculum spanning several classes, an individual class can be pinned to a different venue via TimetableClassVenue — this stays the fallback for any class without an override.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='timetable_slots', to='base.venue'),
        ),
        migrations.AddConstraint(
            model_name='dailyclassexecution',
            constraint=models.UniqueConstraint(fields=('timetable_slot', 'calendar_date', 'lecturer_assignment'), name='unique_execution_per_assignment_per_slot_per_date'),
        ),
        migrations.AddField(
            model_name='dailyclassexecutionvenue',
            name='class_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_venue_overrides', to='base.curriculumclass'),
        ),
        migrations.AddField(
            model_name='dailyclassexecutionvenue',
            name='execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_venues', to='base.dailyclassexecution'),
        ),
        migrations.AddField(
            model_name='dailyclassexecutionvenue',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_execution_overrides', to='base.venue'),
        ),
        migrations.AddField(
            model_name='timetableclassvenue',
            name='class_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_venue_overrides', to='base.curriculumclass'),
        ),
        migrations.AddField(
            model_name='timetableclassvenue',
            name='timetable_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_venues', to='base.timetable'),
        ),
        migrations.AddField(
            model_name='timetableclassvenue',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_timetable_overrides', to='base.venue'),
        ),
        migrations.DeleteModel(
            name='BacklogRegistration',
        ),
        migrations.DeleteModel(
            name='RevaluationRequest',
        ),
        migrations.AlterUniqueTogether(
            name='dailyclassexecutionvenue',
            unique_together={('execution', 'class_link')},
        ),
        migrations.AlterUniqueTogether(
            name='timetableclassvenue',
            unique_together={('timetable_slot', 'class_link')},
        ),
    ]
