# Generated by Django 6.0.6 on 2026-06-18 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_courseevaluation_curriculum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturerevaluation',
            name='curriculum',
        ),
        migrations.AddField(
            model_name='lecturerevaluation',
            name='enrollment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_evaluations', to='base.enrollment'),
            preserve_default=False,
        ),
    ]
