# Generated by Django 6.0.6 on 2026-08-08 20:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_administrativestaff_status_financestaff_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('default_days_per_year', models.PositiveSmallIntegerField(default=21, help_text='Standard entitlement; overridable per staff member via LeaveBalance')),
                ('is_paid', models.BooleanField(default=True)),
                ('requires_document', models.BooleanField(default=False, help_text='e.g. medical certificate for Sick leave')),
                ('requires_substitute_arrangement', models.BooleanField(default=True, help_text='Whether a covering colleague must be named — relevant for teaching staff')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='syllabus',
            options={'verbose_name_plural': 'Syllabus entries'},
        ),
        migrations.AlterUniqueTogether(
            name='syllabus',
            unique_together={('programme', 'course')},
        ),
        migrations.AddField(
            model_name='syllabus',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syllabus_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='proposed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syllabus_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='state',
            field=models.CharField(choices=[('proposed', 'Proposed'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('adjunct', 'Adjunct'), ('retired', 'Retired')], default='proposed', max_length=20),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='year_introduced',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Academic year this entry was approved/introduced into the programme', null=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='syllabus_entries', to='base.course'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='syllabus_entries', to='base.programme'),
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled by Applicant')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_remarks', models.TextField(blank=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
                ('current_approver', models.ForeignKey(blank=True, help_text="Whoever's turn it is in the approval chain right now — null once fully decided", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_leave_approvals', to=settings.AUTH_USER_MODEL)),
                ('substitute_arrangement', models.ForeignKey(blank=True, help_text='Colleague covering duties during this leave, if the leave type requires it', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covering_for_leave_requests', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='base.leavetype')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequestDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='attachments/%Y/%m/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='base.leaverequest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='status',
        ),
        migrations.CreateModel(
            name='LeaveApprovalStep',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(help_text='1 = first approver in the chain, 2 = next, etc.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='base.leaverequest')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('leave_request', 'order')},
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('entitled_days', models.PositiveSmallIntegerField()),
                ('carried_forward_days', models.PositiveSmallIntegerField(default=0, help_text='Unused days carried over from the previous year, if policy allows')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='base.leavetype')),
            ],
            options={
                'unique_together': {('staff', 'leave_type', 'year')},
            },
        ),
    ]
