# Generated by Django 6.0.6 on 2026-06-18 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_lecturerevaluation_curriculum_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lecturerevaluation',
            unique_together={('enrollment', 'lecturer')},
        ),
    ]
