# Generated by Django 6.0.5 on 2026-06-11 09:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_hostel_is_active_remove_hostel_school_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='type',
            new_name='course_type',
        ),
        migrations.AddField(
            model_name='historicaloverdraft',
            name='applied_to',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.studentfeeaccount'),
        ),
        migrations.AddField(
            model_name='historicaloverdraft',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('carried', 'Carried Over'), ('refunded', 'Refunded')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='overdraft',
            name='applied_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='base.studentfeeaccount'),
        ),
        migrations.AddField(
            model_name='overdraft',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('carried', 'Carried Over'), ('refunded', 'Refunded')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='overdraft',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overdrafts', to='base.studentfeeaccount'),
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam_type', models.CharField(choices=[('CAT', 'CAT'), ('MAIN', 'Main Exam'), ('SUPP', 'Supplementary')], max_length=10)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_sessions', to='base.course')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_sessions', to='base.session')),
            ],
            options={
                'unique_together': {('session', 'course', 'exam_type')},
            },
        ),
        migrations.CreateModel(
            name='ExamClash',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resolved', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_clashes', to='base.student')),
                ('session_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clashes_a', to='base.examsession')),
                ('session_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clashes_b', to='base.examsession')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExamVenue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('venue', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venues', to='base.examsession')),
                ('invigilator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invigilation_duties', to='base.lecturer')),
                ('tclass', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_venues', to='base.tclass')),
            ],
            options={
                'unique_together': {('exam_session', 'venue')},
            },
        ),
    ]
