# Generated by Django 6.0.5 on 2026-06-12 10:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_type_course_course_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERPSyncLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type_str', models.CharField(max_length=200)),
                ('event', models.CharField(max_length=100)),
                ('handler', models.CharField(max_length=100)),
                ('attempt', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('attempting', 'Attempting'), ('success', 'Success'), ('failed', 'Failed'), ('error', 'Error'), ('exhausted', 'Exhausted')], max_length=15)),
                ('message', models.TextField(blank=True)),
                ('external_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('meeting_url', models.URLField(blank=True, null=True)),
                ('badge', models.CharField(blank=True, max_length=50, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('source_name', models.CharField(max_length=100)),
                ('rsvp_url', models.URLField(blank=True, null=True)),
                ('rsvp_deadline', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('badge', models.CharField(blank=True, max_length=50, null=True)),
                ('source_url', models.URLField()),
                ('source_name', models.CharField(max_length=100)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AlterField(
            model_name='parentguardian',
            name='id_type',
            field=models.CharField(choices=[('national', 'National ID'), ('passport', 'Passport'), ('birthCert', 'Birth Certificate')], max_length=24),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_type',
            field=models.CharField(choices=[('national', 'National ID'), ('passport', 'Passport'), ('birthCert', 'Birth Certificate')], default='national', max_length=24),
        ),
    ]
