# Generated by Django 6.0.6 on 2026-06-18 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_lecturerevaluation_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overdraft',
            name='account',
        ),
        migrations.RemoveField(
            model_name='overdraft',
            name='applied_to',
        ),
        migrations.RemoveField(
            model_name='overdraft',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='historicalstudentfeeaccount',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='studentfeeaccount',
            name='amount_paid',
        ),
        migrations.DeleteModel(
            name='HistoricalOverDraft',
        ),
        migrations.DeleteModel(
            name='OverDraft',
        ),
    ]
