# Generated by Django 6.0.6 on 2026-08-08 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_leavetype_alter_syllabus_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='syllabus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_entries', to='base.syllabus'),
        ),
        migrations.AddField(
            model_name='historicalcurriculum',
            name='syllabus',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.syllabus'),
        ),
    ]
