# Generated by Django 6.0.8 on 2026-10-03 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_session_results_deadline_alter_office_office_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='active_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.session'),
        ),
    ]
