# Generated by Django 6.0.6 on 2026-06-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_overdraft_account_remove_overdraft_applied_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelallocation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('VACATED', 'Vacated')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
