# Generated by Django 6.0.6 on 2026-08-08 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_curriculum_syllabus_historicalcurriculum_syllabus'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='curriculum',
            unique_together={('syllabus', 'Tclass', 'session')},
        ),
        migrations.RemoveField(
            model_name='historicalcurriculum',
            name='course',
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_entries', to='base.syllabus'),
        ),
        migrations.AlterField(
            model_name='tclass',
            name='courses',
            field=models.ManyToManyField(through='base.Curriculum', to='base.syllabus'),
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='course',
        ),
    ]
