# Generated by Django 6.0.8 on 2026-10-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_institution_active_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='office_type',
            field=models.CharField(choices=[('admissions', 'Admissions'), ('student_support', 'Student Support'), ('registrar', 'Registrar'), ('bursar', 'Bursar / Finance'), ('it_helpdesk', 'IT Helpdesk'), ('finance', 'Finance Office'), ('library', 'Library'), ('hr', 'Human Resources'), ('exam', 'Exam office'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
