# Generated by Django 6.0.8 on 2026-10-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_office_office_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='registration_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='national_id',
            field=models.CharField(blank=True, default='xxxxxxx', max_length=34, null=True, unique=True),
        ),
    ]
