# Generated by Django 6.0.6 on 2026-08-10 10:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_curriculum_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StudentRiskScore',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tier', models.CharField(choices=[('green', 'Green'), ('amber', 'Amber'), ('red', 'Red')], max_length=10)),
                ('primary_risk_factor', models.CharField(blank=True, max_length=100, null=True)),
                ('secondary_risk_factor', models.CharField(blank=True, max_length=100, null=True)),
                ('contributing_factors', models.JSONField(default=dict)),
                ('hard_triggers', models.JSONField(default=list)),
                ('notes', models.JSONField(default=list)),
                ('needs_review', models.BooleanField(default=False)),
                ('reviewed', models.BooleanField(default=False, help_text='Dean has looked at this flag and either acted on it or confirmed no action is needed.')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_remarks', models.TextField(blank=True, help_text='e.g. "Already on payment plan" or "Medical leave already granted"')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_risk_scores', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to='base.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_risk_scores', to='base.session')),
            ],
            options={
                'ordering': ['-score'],
                'unique_together': {('student', 'term')},
            },
        ),
    ]
