# Generated by Django 6.0.6 on 2026-06-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_hostelallocation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='home_adress',
            new_name='home_address',
        ),
        migrations.AddField(
            model_name='student',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='floor',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venue',
            name='ramps',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(max_length=78, unique=True),
        ),
    ]
