# Generated by Django 6.0.6 on 2026-08-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_leaverequest_reason_studentriskscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deferment',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('active', 'Active'), ('reinstated', 'Reinstated'), ('withdrawn', 'Withdrawn')], default='requested', max_length=15),
        ),
        migrations.AlterField(
            model_name='historicaldeferment',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('active', 'Active'), ('reinstated', 'Reinstated'), ('withdrawn', 'Withdrawn')], default='requested', max_length=15),
        ),
    ]
