# Generated by Django 6.0.6 on 2026-08-11 17:14

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_historicalresult_state_result_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppraisalCycle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('academic_year', models.CharField(help_text='Format: "2025/2026"', max_length=9)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('self_assessment_deadline', models.DateField()),
                ('hod_review_deadline', models.DateField()),
                ('dean_approval_deadline', models.DateField()),
                ('teaching_weight', models.DecimalField(decimal_places=2, default=Decimal('0.40'), max_digits=3)),
                ('research_weight', models.DecimalField(decimal_places=2, default=Decimal('0.30'), max_digits=3)),
                ('service_weight', models.DecimalField(decimal_places=2, default=Decimal('0.30'), max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('academic_year',)},
            },
        ),
        migrations.CreateModel(
            name='PerformanceAppraisal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('self_submitted', 'Self-Assessment Submitted'), ('hod_reviewed', 'HOD Reviewed'), ('dean_approved', 'Dean Approved'), ('finalized', 'Finalized'), ('disputed', 'Disputed by Lecturer')], default='draft', max_length=20)),
                ('self_assessment_summary', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('challenges_faced', models.TextField(blank=True)),
                ('professional_development', models.TextField(blank=True, help_text='Courses, conferences, certifications completed this cycle')),
                ('goals_for_next_cycle', models.TextField(blank=True)),
                ('self_rating', models.CharField(blank=True, choices=[('outstanding', 'Outstanding'), ('exceeds_expectations', 'Exceeds Expectations'), ('meets_expectations', 'Meets Expectations'), ('needs_improvement', 'Needs Improvement'), ('unsatisfactory', 'Unsatisfactory')], max_length=25, null=True)),
                ('self_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('average_student_rating', models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot average of LecturerEvaluation.rating for this cycle', max_digits=3, null=True)),
                ('courses_taught_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('teaching_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('publications_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('research_projects_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('research_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('administrative_roles_summary', models.TextField(blank=True, help_text='Committee memberships, AcademicAppointments held, other service')),
                ('service_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('reviewer_comments', models.TextField(blank=True)),
                ('reviewer_rating', models.CharField(blank=True, choices=[('outstanding', 'Outstanding'), ('exceeds_expectations', 'Exceeds Expectations'), ('meets_expectations', 'Meets Expectations'), ('needs_improvement', 'Needs Improvement'), ('unsatisfactory', 'Unsatisfactory')], max_length=25, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('final_rating', models.CharField(blank=True, choices=[('outstanding', 'Outstanding'), ('exceeds_expectations', 'Exceeds Expectations'), ('meets_expectations', 'Meets Expectations'), ('needs_improvement', 'Needs Improvement'), ('unsatisfactory', 'Unsatisfactory')], max_length=25, null=True)),
                ('final_remarks', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('dispute_remarks', models.TextField(blank=True)),
                ('disputed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisals_approved', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appraisals', to='base.appraisalcycle')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_appraisals', to='base.lecturer')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisals_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cycle__start_date'],
                'unique_together': {('lecturer', 'cycle')},
            },
        ),
        migrations.CreateModel(
            name='AppraisalGoal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('achieved', 'Achieved'), ('partially_achieved', 'Partially Achieved'), ('not_achieved', 'Not Achieved')], default='not_started', max_length=20)),
                ('outcome_notes', models.TextField(blank=True)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='base.performanceappraisal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppraisalDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='attachments/%Y/%m/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='base.performanceappraisal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
