# Generated by Django 6.0.6 on 2026-09-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_academicappointment_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='offered',
            field=models.IntegerField(default=1, help_text='Year of study this unit is typically scheduled.'),
        ),
    ]
