# Generated by Django 6.0.6 on 2026-09-05 08:59

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_syllabus_offered'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingScale',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_default', models.BooleanField(default=False, help_text='Used by any Course with grading_scale left blank. Only one scale should have this set — enforced in clean().')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='complaint',
            name='current_level',
            field=models.CharField(blank=True, choices=[('Department', 'Department Level (HOD / Lecturer)'), ('School', 'School / Faculty Level (Dean)'), ('StudentAffairs', 'Dean of Students'), ('Division', 'Division Level (Registrar Academic Affairs)'), ('Senate', 'University Senate / Vice-Chancellor Executive'), ('External', 'External Body / Ombudsman / Legal Counsel')], help_text="Where in this category's escalation path the complaint currently sits. Set on first save, advanced by escalate().", max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='sla_due_at',
            field=models.DateTimeField(blank=True, help_text="When the current level's SLA window expires. The scheduled job escalates anything with sla_due_at in the past and status != 'Resolved'.", null=True),
        ),
        migrations.AddField(
            model_name='complaintescalationhistory',
            name='is_automatic',
            field=models.BooleanField(default=False, help_text='True if a scheduled job escalated this because the SLA expired; False if a staff member escalated it manually.'),
        ),
        migrations.AddField(
            model_name='course',
            name='pass_mark',
            field=models.PositiveIntegerField(default=40, help_text='Minimum score to pass this specific course. Override per course — e.g. a professional/regulated unit might require 50.'),
        ),
        migrations.AddField(
            model_name='graduation',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='graduation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_graduations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='graduation',
            name='nominated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='graduation',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='graduation',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_graduations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcomplaint',
            name='current_level',
            field=models.CharField(blank=True, choices=[('Department', 'Department Level (HOD / Lecturer)'), ('School', 'School / Faculty Level (Dean)'), ('StudentAffairs', 'Dean of Students'), ('Division', 'Division Level (Registrar Academic Affairs)'), ('Senate', 'University Senate / Vice-Chancellor Executive'), ('External', 'External Body / Ombudsman / Legal Counsel')], help_text="Where in this category's escalation path the complaint currently sits. Set on first save, advanced by escalate().", max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalcomplaint',
            name='sla_due_at',
            field=models.DateTimeField(blank=True, help_text="When the current level's SLA window expires. The scheduled job escalates anything with sla_due_at in the past and status != 'Resolved'.", null=True),
        ),
        migrations.AlterField(
            model_name='complaintescalationhistory',
            name='escalated_by',
            field=models.ForeignKey(blank=True, help_text='Null when is_automatic=True — the Celery job escalated this, not a person.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initiated_escalations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complaintescalationhistory',
            name='escalated_from_level',
            field=models.CharField(choices=[('Department', 'Department Level (HOD / Lecturer)'), ('School', 'School / Faculty Level (Dean)'), ('StudentAffairs', 'Dean of Students'), ('Division', 'Division Level (Registrar Academic Affairs)'), ('Senate', 'University Senate / Vice-Chancellor Executive'), ('External', 'External Body / Ombudsman / Legal Counsel')], max_length=30),
        ),
        migrations.AlterField(
            model_name='complaintescalationhistory',
            name='escalated_to_level',
            field=models.CharField(choices=[('Department', 'Department Level (HOD / Lecturer)'), ('School', 'School / Faculty Level (Dean)'), ('StudentAffairs', 'Dean of Students'), ('Division', 'Division Level (Registrar Academic Affairs)'), ('Senate', 'University Senate / Vice-Chancellor Executive'), ('External', 'External Body / Ombudsman / Legal Counsel')], max_length=30),
        ),
        migrations.AddField(
            model_name='course',
            name='grading_scale',
            field=models.ForeignKey(blank=True, help_text="Which A/B/C/D/E (or pass/fail) band set applies to this course's results. Leave blank to use the institution default.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='base.gradingscale'),
        ),
        migrations.CreateModel(
            name='HistoricalGraduation',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('record_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('nominated', 'Nominated'), ('verified', 'Verified'), ('approved', 'Approved'), ('conferred', 'Conferred')], default='nominated', max_length=20)),
                ('final_classification', models.CharField(choices=[('First_Class', 'First Class Honours / Distinction'), ('Second_Upper', 'Second Class Honours (Upper Division)'), ('Second_Lower', 'Second Class Honours (Lower Division)'), ('Pass', 'Pass (Standard Undergraduate or Postgraduate award)'), ('Satisfied', 'Satisfied ( Doctorates/PhDs)')], help_text='Official degree classification mapped to CUE data guidelines.', max_length=30)),
                ('with_honours', models.BooleanField(default=True, help_text='Flag indicating if the degree was conferred with an Honours distinction.')),
                ('thesis_title', models.TextField(blank=True, help_text='Compulsory for Postgraduate (Masters/PhD) returns', null=True)),
                ('nominated_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('Tclass', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.tclass')),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.student')),
                ('verified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Graduation Record',
                'verbose_name_plural': 'historical Graduation Records',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='GradingBand',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('min_score', models.PositiveIntegerField(help_text="Lowest score (inclusive) that earns this band's grade points.")),
                ('grade_points', models.DecimalField(decimal_places=2, max_digits=3)),
                ('label', models.CharField(blank=True, help_text="e.g. 'A', 'B+' — display only.", max_length=5)),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='base.gradingscale')),
            ],
            options={
                'ordering': ['-min_score'],
                'unique_together': {('scale', 'min_score')},
            },
        ),
    ]
