# Generated by Django 6.0.6 on 2026-09-08 07:09

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_historicalgradingband_historicalgradingscale'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightingScheme',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_default', models.BooleanField(default=False, help_text='Institution-wide fallback when neither a Course nor a specific Curriculum offering specifies its own scheme.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='historicalgradingscale',
            name='history_user',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='credits_earned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='grade_points_earned',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='graded_scale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='graded_against', to='base.gradingscale'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='graded_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Score used to decide pass/fail and grade points. Frozen once — editing Course.pass_mark or the grading scale later never changes this.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='pass_mark_applied',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalenrollment',
            name='credits_earned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalenrollment',
            name='grade_points_earned',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='historicalenrollment',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalenrollment',
            name='graded_scale',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.gradingscale'),
        ),
        migrations.AddField(
            model_name='historicalenrollment',
            name='graded_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Score used to decide pass/fail and grade points. Frozen once — editing Course.pass_mark or the grading scale later never changes this.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='historicalenrollment',
            name='pass_mark_applied',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='relationship',
            field=models.CharField(choices=[('parent', 'Parent'), ('guardian', 'Guardian'), ('spouse', 'Spouse'), ('child', 'Child'), ('relative', 'Relative'), ('other', 'Other')], max_length=78),
        ),
        migrations.CreateModel(
            name='WeightingComponent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('result_type', models.CharField(choices=[('C', 'Cat'), ('E', 'Exams'), ('P', 'Practicals'), ('A', 'Assignments'), ('Q', 'Quizzes'), ('PR', 'Projects')], max_length=2)),
                ('weight_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('aggregation', models.CharField(choices=[('average_all', 'Average all submissions'), ('best_n', 'Average the best N submissions'), ('sum', 'Sum all submissions'), ('latest', 'Most recent submission only')], default='average_all', help_text="How multiple results of this type combine into this component's score. e.g. three CATs: average all three, or drop the worst and average the best 2.", max_length=15)),
                ('expected_count', models.PositiveSmallIntegerField(blank=True, help_text="How many results of this type the lecturer plans to give (e.g. 3 CATs). REQUIRED for 'best_n' — without knowing the total, the system can't tell 'still waiting on more CATs' apart from 'that's all of them.' Optional for the other strategies; leave blank if any number of submissions should count as complete.", null=True)),
                ('best_n_count', models.PositiveSmallIntegerField(blank=True, help_text="Only used when aggregation='best_n' — how many of the top scores to average, e.g. 2 (best 2 of 3).", null=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='base.weightingscheme')),
            ],
            options={
                'unique_together': {('scheme', 'result_type')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalCourse',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('record_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('deleted', models.BooleanField(default=False)),
                ('course_name', models.CharField(max_length=255)),
                ('course_code', models.CharField(db_index=True, help_text='e.g., CCS 401, BIL 810', max_length=74)),
                ('course_type', models.CharField(choices=[('C', 'Core'), ('E', 'Elective'), ('CC', 'Common Unit'), ('P', 'Practical / Laboratory Unit'), ('IA', 'Industrial Attachment / Internship'), ('TP', 'Teaching Practice / Field Practicum'), ('PR', 'Postgraduate Research Thesis / Dissertation'), ('ST', 'Specialised Seminar / Independent Study')], db_index=True, default='C', max_length=45)),
                ('credits', models.IntegerField(default=3, help_text='Undergraduate units default to 3 credits. PhD Research can scale up to 15+ credits.')),
                ('lecture_hours_per_week', models.PositiveIntegerField(default=3)),
                ('practical_hours_per_week', models.PositiveIntegerField(default=0, help_text='Required if course_type is (Practical/Lab).')),
                ('attachment_duration_weeks', models.PositiveIntegerField(default=0, help_text='Mandatory weeks for industrial attach/practicums. Usually 8-12 weeks under CUE guidelines.')),
                ('is_externally_assessed', models.BooleanField(default=False, help_text='Requires an appointed external university assessor/supervisor field-visit grade signoff.')),
                ('is_postgraduate_only', models.BooleanField(default=False, help_text='Hard lock variable preventing undergraduate students from registering into this code.')),
                ('requires_defense_panel', models.BooleanField(default=False, help_text='Mandatory for Thesis/Dissertation options. Triggers Senate Board of Examiners appointment workflows.')),
                ('expected_competencies', models.JSONField(blank=True, default=list, help_text='List of core skill competencies mapped to this course for UCBEF checks.', null=True)),
                ('unesco_isced', models.CharField(blank=True, choices=[('0011', 'Basic programmes and qualifications'), ('0021', 'Literacy and numeracy'), ('0031', 'Personal skills and development'), ('0099', 'Generic programmes and qualifications not elsewhere classified'), ('0111', 'Education science'), ('0112', 'Training for pre-school teachers'), ('0113', 'Teacher training without subject specialisation'), ('0114', 'Teacher training with subject specialisation'), ('0188', 'Inter-disciplinary programmes involving education'), ('0211', 'Audio-visual techniques and media production'), ('0212', 'Fashion, interior and industrial design'), ('0213', 'Fine arts'), ('0214', 'Handicrafts'), ('0215', 'Music and performing arts'), ('0221', 'Religion and theology'), ('0222', 'History and archaeology'), ('0223', 'Philosophy and ethics'), ('0231', 'Language acquisition'), ('0232', 'Literature and linguistics'), ('0288', 'Inter-disciplinary programmes involving arts and humanities'), ('0311', 'Economics'), ('0312', 'Political sciences and civics'), ('0313', 'Psychology'), ('0314', 'Sociology and cultural studies'), ('0321', 'Journalism and reporting'), ('0322', 'Library, information and archival studies'), ('0388', 'Inter-disciplinary programmes involving social sciences/journalism'), ('0411', 'Accounting and taxation'), ('0412', 'Finance, banking and insurance'), ('0413', 'Management and administration'), ('0414', 'Marketing and advertising'), ('0415', 'Secretarial and office work'), ('0416', 'Wholesale and retail sales'), ('0417', 'Work skills'), ('0421', 'Law'), ('0488', 'Inter-disciplinary programmes involving business/admin/law'), ('0511', 'Biology'), ('0512', 'Biochemistry'), ('0521', 'Environmental sciences'), ('0522', 'Natural environments and wildlife'), ('0531', 'Chemistry'), ('0532', 'Earth sciences'), ('0533', 'Physics'), ('0541', 'Mathematics'), ('0542', 'Statistics'), ('0588', 'Inter-disciplinary programmes involving natural sciences/maths'), ('0611', 'Computer use (Basic IT/Applications)'), ('0612', 'Database and network design and administration'), ('0613', 'Software and applications development and analysis (Computer Science)'), ('0688', 'Inter-disciplinary programmes involving ICTs'), ('0711', 'Chemical engineering and processes'), ('0712', 'Environmental protection technology'), ('0713', 'Electricity and energy'), ('0714', 'Electronics and automation (Mechatronics/Hardware Engineering)'), ('0715', 'Mechanics and metal trades'), ('0716', 'Motor vehicles, ships and aircraft (Aeronautical/Automotive)'), ('0721', 'Food processing'), ('0722', 'Materials (glass, paper, plastic and wood)'), ('0723', 'Textiles (clothes, footwear and leather)'), ('0724', 'Mining and extraction'), ('0731', 'Architecture and town planning'), ('0732', 'Building and civil engineering'), ('0788', 'Inter-disciplinary programmes involving engineering/construction'), ('0811', 'Crop and livestock production'), ('0812', 'Horticulture'), ('0821', 'Forestry'), ('0831', 'Fisheries'), ('0841', 'Veterinary'), ('0888', 'Inter-disciplinary programmes involving agriculture/veterinary'), ('0911', 'Dental studies'), ('0912', 'Medicine (Clinical Medicine/Surgery/MBChB)'), ('0913', 'Nursing and midwifery'), ('0914', 'Medical diagnostic and treatment technology (Radiology/Lab Tech)'), ('0915', 'Therapy and rehabilitation (Physiotherapy)'), ('0916', 'Pharmacy'), ('0917', 'Traditional and complementary medicine and therapy'), ('0921', 'Care of elderly and of disabled adults'), ('0922', 'Child care and youth services'), ('0923', 'Social work and counselling'), ('0988', 'Inter-disciplinary programmes involving health and welfare'), ('1011', 'Domestic services'), ('1012', 'Hair and beauty services'), ('1013', 'Hotel, restaurants and catering'), ('1014', 'Sports'), ('1015', 'Travel, tourism and leisure'), ('1021', 'Community sanitation'), ('1022', 'Occupational health and safety'), ('1031', 'Military science and defence'), ('1032', 'Protection of persons and property (Security Management/Police)'), ('1041', 'Transport services (Logistics/Aviation operations)'), ('1088', 'Inter-disciplinary programmes involving services')], help_text='Standardized UNESCO tag for this specific subject matter.', max_length=123, null=True)),
                ('offered', models.IntegerField(default=1, help_text='Year of study this unit is typically scheduled.')),
                ('pass_mark', models.PositiveIntegerField(default=40, help_text='Minimum score to pass this specific course. Override per course — e.g. a professional/regulated unit might require 50.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.department')),
                ('grading_scale', models.ForeignKey(blank=True, db_constraint=False, help_text="Which A/B/C/D/E (or pass/fail) band set applies to this course's results. Leave blank to use the institution default.", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.gradingscale')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('weighting_scheme', models.ForeignKey(blank=True, db_constraint=False, help_text='Default CAT/Exam/etc. weighting for this course. Leave blank to use the institution default scheme.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.weightingscheme')),
            ],
            options={
                'verbose_name': 'historical Course Module',
                'verbose_name_plural': 'historical Course Modules',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='course',
            name='weighting_scheme',
            field=models.ForeignKey(blank=True, help_text='Default CAT/Exam/etc. weighting for this course. Leave blank to use the institution default scheme.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='base.weightingscheme'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='weighting_scheme_override',
            field=models.ForeignKey(blank=True, help_text="Lets whoever teaches THIS class this session use a different weighting than the course default — e.g. one lecturer runs 40% CAT / 60% Exam for their section while the course default is 30/70. Leave blank to inherit the course's scheme.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='curricula_overriding', to='base.weightingscheme'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='weighting_scheme_used',
            field=models.ForeignKey(blank=True, help_text="Which scheme actually produced graded_score — frozen alongside the other grading fields for the same reason: changing the scheme later shouldn't reinterpret old grades.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='weighted_against', to='base.weightingscheme'),
        ),
        migrations.AddField(
            model_name='historicalcurriculum',
            name='weighting_scheme_override',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="Lets whoever teaches THIS class this session use a different weighting than the course default — e.g. one lecturer runs 40% CAT / 60% Exam for their section while the course default is 30/70. Leave blank to inherit the course's scheme.", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.weightingscheme'),
        ),
        migrations.AddField(
            model_name='historicalenrollment',
            name='weighting_scheme_used',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="Which scheme actually produced graded_score — frozen alongside the other grading fields for the same reason: changing the scheme later shouldn't reinterpret old grades.", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.weightingscheme'),
        ),
        migrations.DeleteModel(
            name='HistoricalGradingBand',
        ),
        migrations.DeleteModel(
            name='HistoricalGradingScale',
        ),
    ]
